
### Get All Categories
GET http://localhost:3000/api/categories
X-API-KEY: RAHASIA
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}


### Update New Category
GET http://localhost:3000/api/categories/2
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

### Update New Category
PUT http://localhost:3000/api/categories/2
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": ""
}


### Update New Category
DELETE http://localhost:3000/api/categories/100
X-API-KEY: RAHASIA
Accept: application/json
Content-Type: application/json